# Generated by Django 5.2 on 2025-11-18 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_acuerdo', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProductos.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Producto-Proveedor',
                'verbose_name_plural': 'Productos-Proveedores',
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
