# Generated by Django 5.2 on 2025-12-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproveedor',
            name='fecha_acuerdo',
        ),
    ]
