# Generated by Django 5.2 on 2025-12-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0002_remove_productoproveedor_fecha_acuerdo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproveedor',
            name='precio',
        ),
    ]
