# Generated by Django 5.2 on 2025-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProveedores', '0003_remove_productoproveedor_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
