# Generated by Django 5.2 on 2025-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProductos', '0002_alter_productos_codproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='iva',
            field=models.DecimalField(choices=[(21.0, '21%'), (10.5, '10.5%'), (27.0, '27%'), (0.0, 'Exento (0%)')], decimal_places=2, default=21.0, max_digits=4),
        ),
    ]
