# Generated by Django 5.2 on 2025-12-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProductos', '0003_productos_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
