# Generated by Django 5.2 on 2025-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='observacion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
