# Generated by Django 5.2 on 2025-12-06 00:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVentas', '0004_remove_detalleventa_subtotal_con_iva_venta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal_con_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
