# Generated by Django 5.2 on 2025-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCompras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='subtotal',
            new_name='iva_monto',
        ),
        migrations.AddField(
            model_name='compra',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_con_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='subtotal_con_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
