# Generated by Django 5.2 on 2025-12-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCompras', '0002_rename_subtotal_detallecompra_iva_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='compra',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='observacion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='subtotal_con_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
