# Generated by Django 5.2 on 2025-12-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCompras', '0003_compra_estado_alter_compra_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
    ]
